import Foundation
import Testing
@testable import MultiTaskCore

@Suite("Markdown — line splitting")
struct MarkdownLineTests {

    @Test("CRLF is one break, not two")
    func crlfIsOneBreak() {
        // The bug this exists to prevent: `components(separatedBy: .newlines)`
        // yields an empty line between every real one for a CRLF document, and
        // since an empty line ends a paragraph, everything after the first line
        // silently disappears.
        #expect(Markdown.lines(of: "a\r\nb\r\nc") == ["a", "b", "c"])
        #expect(Markdown.lines(of: "a\nb") == ["a", "b"])
        #expect(Markdown.lines(of: "a\rb") == ["a", "b"])
        #expect(Markdown.lines(of: "a\r\n\r\nb") == ["a", "", "b"])
    }

    @Test("A CRLF document keeps its whole first paragraph")
    func crlfParagraphSurvives() throws {
        let doc = "# Title\r\n\r\nA project that watches your agents\r\nacross many repos.\r\n\r\n## Install\r\n"
        let paragraph = try #require(Markdown.firstParagraph(of: doc))
        #expect(paragraph == "A project that watches your agents across many repos.")
    }

    @Test("Trimming removes carriage returns, which .whitespaces does not")
    func trimHandlesCarriageReturn() {
        #expect(Markdown.trim("- [ ] Ship the thing\r") == "- [ ] Ship the thing")
    }

    @Test("Headings are recognised by level, and near-misses aren't")
    func headingDetection() {
        #expect(Markdown.headingLevel("## Success metrics") == 2)
        #expect(Markdown.headingLevel("#Heading") == nil)      // no space
        #expect(Markdown.headingLevel("####### too deep") == nil)
        #expect(Markdown.headingTitle("### Jobs-to-be-done") == "Jobs-to-be-done")
    }
}

@Suite("Markdown — sections")
struct MarkdownSectionTests {
    let doc = """
    # Product

    > Generated by something.

    ## Register

    product — a daily-use reading tool.

    ## One-liner

    Saga is a reading app that remembers where your attention went.

    ## Users

    ### Primary

    Committed nonfiction readers.

    ## Product Purpose

    Most reading apps optimise for saving.

    ### Success metrics

    - Completion rate: % finished within 30 days
    - Highlight-return rate: ≥ 35% at 30 days

    ## Design Principles

    - The text is the interface.
    - Calm over engagement.
    """

    @Test("Reads a section by name, stopping at the next same-level heading")
    func readsSection() throws {
        let oneLiner = try #require(Markdown.section("One-liner", in: doc))
        #expect(oneLiner.contains("Saga is a reading app"))
        #expect(!oneLiner.contains("Users"))
        #expect(!oneLiner.contains("daily-use reading tool"))
    }

    @Test("A section swallows deeper subsections but not siblings")
    func nestingRespected() throws {
        let users = try #require(Markdown.section("Users", in: doc))
        #expect(users.contains("Primary"))
        #expect(users.contains("Committed nonfiction readers"))
        #expect(!users.contains("Most reading apps"))
    }

    @Test("Matching is case-insensitive and level-insensitive")
    func flexibleMatching() throws {
        // "Success metrics" is an h3 here; callers shouldn't have to know that.
        let metrics = try #require(Markdown.section("success METRICS", in: doc))
        #expect(metrics.contains("Completion rate"))
    }

    @Test("A missing section is nil, not empty")
    func missingSection() {
        #expect(Markdown.section("Nonexistent", in: doc) == nil)
    }

    @Test("Bullets come back cleaned of markdown")
    func bulletExtraction() throws {
        let principles = try #require(Markdown.section("Design Principles", in: doc))
        #expect(Markdown.bullets(in: principles) == [
            "The text is the interface.",
            "Calm over engagement."
        ])
    }

    @Test("Headings inside a code fence don't end a section")
    func fencedHeadingsIgnored() throws {
        let fenced = """
        ## Setup

        ```sh
        # not a heading
        make install
        ```

        Done.

        ## Next
        """
        let setup = try #require(Markdown.section("Setup", in: fenced))
        #expect(setup.contains("make install"))
        #expect(setup.contains("Done."))
        #expect(!setup.contains("## Next"))
    }
}

@Suite("Markdown — task items")
struct MarkdownTaskTests {

    @Test("Counts checked and unchecked items alike")
    func countsBoth() {
        let items = Markdown.taskItems(in: Fixtures.roadmapWithTasks)
        #expect(items.count == 7)
        #expect(items.filter(\.isChecked).count == 2)
        #expect(items.filter { !$0.isChecked }.count == 5)
    }

    @Test("Recognises every bullet form")
    func bulletForms() {
        let items = Markdown.taskItems(in: Fixtures.roadmapWithTasks)
        #expect(items.map(\.text).contains("Read the audit log"))          // *
        #expect(items.map(\.text).contains("Render orchestration waves"))  // +
        #expect(items.map(\.text).contains("Discover worktrees"))          // 1.
        #expect(items.map(\.text).contains("Parse the delegate roster"))   // 2)
    }

    @Test("Accepts x and X, rejects other markers")
    func checkboxMarkers() {
        #expect(Markdown.taskItem(in: "- [x] done")?.isChecked == true)
        #expect(Markdown.taskItem(in: "- [X] done")?.isChecked == true)
        #expect(Markdown.taskItem(in: "- [ ] todo")?.isChecked == false)
        #expect(Markdown.taskItem(in: "- [-] neither") == nil)
        #expect(Markdown.taskItem(in: "-[ ] no space") == nil)
        #expect(Markdown.taskItem(in: "- [ ]") == nil)
    }

    @Test("Items inside a code fence are examples, not work")
    func fencedItemsIgnored() {
        let doc = """
        - [ ] Real task

        ```md
        - [ ] Example in a snippet
        - [x] Another example
        ```
        """
        let items = Markdown.taskItems(in: doc)
        #expect(items.map(\.text) == ["Real task"])
    }
}

@Suite("Path handling — cross-platform")
struct PathPortabilityTests {

    @Test("Both separators are understood, so a Windows path yields a name")
    func lastComponentHandlesBackslashes() {
        // The bug this prevents: a `/`-only split returns the whole string, so
        // every project name on Windows would be its full path.
        #expect(FileSupport.lastComponent(of: #"C:\Users\joe\projects\app"#) == "app")
        #expect(FileSupport.lastComponent(of: "/home/joe/projects/app") == "app")
        #expect(FileSupport.lastComponent(of: #"C:\Users\joe\projects\app\"#) == "app")
        #expect(FileSupport.lastComponent(of: "/home/joe/projects/app/") == "app")
        // A mixed path is legal on Windows and must still resolve.
        #expect(FileSupport.lastComponent(of: #"C:\Users\joe/projects/app"#) == "app")
    }

    @Test("Comparison normalises separators")
    func normalisation() {
        #expect(FileSupport.normalise(#"C:\work\app\"#) == "C:/work/app")
        #expect(FileSupport.pathsEqual(#"C:\work\app"#, "C:/work/app"))
        #expect(!FileSupport.pathsEqual("/a/b", "/a/c"))
    }

    @Test("Containment respects boundaries, not string prefixes")
    func containment() {
        #expect(FileSupport.path("/home/joe/app/src/x.swift", isInside: "/home/joe/app"))
        #expect(FileSupport.path("/home/joe/app", isInside: "/home/joe/app"))
        // The classic false positive: a sibling whose name starts the same way.
        #expect(!FileSupport.path("/home/joe/app-other/x.swift", isInside: "/home/joe/app"))
        #expect(FileSupport.path(#"C:\work\app\src"#, isInside: "C:/work/app"))
    }

    @Test("A drive root is no more a project than / is")
    func driveRootIsNotAProject() {
        #expect(!FileSupport.isPlausibleProjectPath("/"))
        #expect(!FileSupport.isPlausibleProjectPath(#"C:\"#))
        #expect(!FileSupport.isPlausibleProjectPath("C:"))
        #expect(FileSupport.isPlausibleProjectPath(#"C:\work\app"#))
    }

    @Test("File identity falls back when the platform has no inodes")
    func fileIdentityHasAFallback() {
        let dir = TempDir()
        dir.write("hello", to: "a.txt")
        let identity = FileSupport.fileIdentity(ofPath: dir.path("a.txt"))
        // On this platform inodes exist; the point is that *something* non-zero
        // comes back, because a zero pair means rotation can never be detected.
        #expect(identity.device != 0 || identity.inode != 0)
        #expect(FileSupport.fileIdentity(ofPath: "/nonexistent") == (0, 0))
    }

    @Test("git is looked for on PATH, which is what the user's shell would use")
    func gitFromPath() {
        let resolved = GitRunner.resolveGit()
        #expect(resolved.hasSuffix("git") || resolved.hasSuffix("git.exe"))
        #expect(FileManager.default.isExecutableFile(atPath: resolved))
    }
}
