import Foundation
import Testing
@testable import MultiTaskCore

extension Fixtures {
    /// Shaped exactly like a `project-starter-pack` output: the title, the
    /// generated blockquote, then Register *before* One-liner. That ordering is
    /// the whole reason positional reading fails here.
    static let productBrief = """
    # Product

    > Generated by `project-starter-pack`. This is the source of truth for **who this product is for**.

    ## Register

    product — a daily-use reading tool where earned familiarity beats novelty.

    ## One-liner

    Saga is a reading app for long-form nonfiction that remembers where your attention went.

    ## Users

    ### Primary

    Committed nonfiction readers.

    ### Jobs-to-be-done

    - **Finish** the long thing I started, across devices.
    - **Capture** a passage in one gesture.

    ## Product Purpose

    Most reading apps optimise for saving rather than finishing.

    ### Success metrics

    - Completion rate: % of started long-reads finished within 30 days
    - Highlight-return rate: ≥ 35% at 30 days

    ## Design Principles

    - The text is the interface.
    - Calm over engagement.

    ## Anti-references

    - Kindle — closed annotation model.
    """
}

@Suite("BriefReader")
struct BriefReaderTests {

    @Test("The one-liner is the goal — not the first paragraph, which is the register")
    func oneLinerNotRegister() throws {
        let brief = BriefReader.parse(Fixtures.productBrief)
        let oneLiner = try #require(brief.oneLiner)

        #expect(oneLiner.hasPrefix("Saga is a reading app"))
        // The bug this replaces: positional reading skips the title and the
        // generated blockquote as chrome and lands on Register.
        #expect(!oneLiner.contains("daily-use reading tool"))
        #expect(brief.register?.hasPrefix("product —") == true)
    }

    @Test("Reads the sections that say what done looks like")
    func acceptanceContext() {
        let brief = BriefReader.parse(Fixtures.productBrief)

        #expect(brief.jobsToBeDone.count == 2)
        #expect(brief.jobsToBeDone[0].hasPrefix("Finish the long thing"))
        #expect(brief.successMetrics.count == 2)
        #expect(brief.successMetrics[1].contains("35%"))
        #expect(brief.purpose?.hasPrefix("Most reading apps") == true)
    }

    @Test("Reads the sections a reviewer should be judged against")
    func reviewContext() {
        let brief = BriefReader.parse(Fixtures.productBrief)
        #expect(brief.designPrinciples == ["The text is the interface.", "Calm over engagement."])
        #expect(brief.antiReferences.count == 1)
    }

    @Test("An unfilled template reads as empty, not as content")
    func placeholdersAreNotContent() {
        let template = """
        # Product

        ## One-liner

        {{ONE_LINER}}

        ## Design Principles

        {{DESIGN_PRINCIPLES}}
        """
        let brief = BriefReader.parse(template)
        #expect(brief.oneLiner == nil)
        #expect(brief.isEmpty)
    }

    @Test("Reports which briefs a project carries, and which it doesn't")
    func briefSet() {
        let dir = TempDir()
        dir.write(Fixtures.productBrief, to: "app/PRODUCT.md")
        dir.write("# Code", to: "app/CODE.md")

        let (brief, set) = BriefReader().read(projectPath: dir.path("app"))
        #expect(brief?.oneLiner != nil)
        #expect(set.product)
        #expect(set.code)
        #expect(set.design == false)
        #expect(set.meetsMinimum)
        #expect(set.missing == ["DESIGN.md"])
    }

    @Test("A project with nothing at all reports the minimum it's missing")
    func noBrief() {
        let dir = TempDir()
        dir.makeDirectory("app")
        let (brief, set) = BriefReader().read(projectPath: dir.path("app"))

        #expect(brief == nil)
        #expect(set.meetsMinimum == false)
        #expect(set.missing.contains("PRODUCT.md"))
    }

    @Test("A bare README is read as context, without being a product brief")
    func readmeCounts() {
        let dir = TempDir()
        dir.makeDirectory("app")
        dir.write("# Demo\n\nA thing that does a thing.", to: "app/README.md")
        let (_, set) = BriefReader().read(projectPath: dir.path("app"))

        #expect(set.readme)
        #expect(set.meetsMinimum)
        // Still worth prompting for once — just never as a status.
        #expect(set.hasProductBrief == false)
        #expect(set.missing.contains("PRODUCT.md"))
    }

    @Test("CLAUDE.md alone counts — instructions for an agent describe the project too")
    func claudeMdCounts() {
        let dir = TempDir()
        dir.makeDirectory("app")
        dir.write("# Claude Code Instructions", to: "app/CLAUDE.md")
        let (_, set) = BriefReader().read(projectPath: dir.path("app"))
        #expect(set.claude)
        #expect(set.meetsMinimum)
    }
}

@Suite("ProjectAssembler — the status ladder")
struct ProjectStatusTests {
    let now = Fixtures.auditNow

    private func record(_ name: String = "app") -> ProjectRecord {
        ProjectRecord(id: "app-1", name: name, path: "/home/user/projects/app", createdAt: now)
    }

    private func briefed() -> BriefSet {
        var set = BriefSet()
        set.product = true
        return set
    }

    private func verdict(sessions: [Session] = [],
                         repository: RepositoryState? = nil,
                         briefs: BriefSet? = nil,
                         nextSteps: Int = 0,
                         lastActivity: Date? = nil) -> ProjectAssembler.StatusVerdict {
        ProjectAssembler.status(record: record(),
                                sessions: sessions,
                                repository: repository,
                                briefs: briefs ?? briefed(),
                                nextStepCount: nextSteps,
                                lastActivity: lastActivity ?? now,
                                now: now)
    }

    @Test("A stalled converge needs you, ahead of everything else")
    func convergeOutranksAll() {
        let stalled = RepositoryState(path: "/p", name: "app",
                                      conflictMarkers: [".converge-conflict-ai-claude"],
                                      scannedAt: now)
        // Even with a session actively working, a broken converge wins.
        let result = verdict(sessions: [Session.stub(id: "s", lastActivity: now, status: .working)],
                             repository: stalled)
        #expect(result.status == .needsYou)
        #expect(result.reason.contains("Converge stalled"))
    }

    @Test("A waiting session needs you, and the reason names why")
    func waitingSession() {
        let waiting = Session.stub(id: "s", lastActivity: now, waiting: .approval,
                                   evidence: .hook, status: .needsAttention)
        let result = verdict(sessions: [waiting])
        #expect(result.status == .needsYou)
        #expect(result.reason.contains("Needs approval"))
    }

    @Test("Several waiting sessions report the most urgent, and how many more")
    func multipleWaiting() {
        let sessions = [
            Session.stub(id: "a", lastActivity: now, waiting: .done, evidence: .hook, status: .needsAttention),
            Session.stub(id: "b", lastActivity: now, waiting: .approval, evidence: .hook, status: .needsAttention)
        ]
        let result = verdict(sessions: sessions)
        #expect(result.reason.contains("Needs approval"))   // outranks "finished"
        #expect(result.reason.contains("+1 more"))
    }

    @Test("A live session is working, and says what it's running")
    func working() {
        var session = Session.stub(id: "s", lastActivity: now, status: .working)
        session.lastToolName = "Bash"
        let result = verdict(sessions: [session])
        #expect(result.status == .working)
        #expect(result.reason.contains("Bash"))
    }

    @Test("Unchecked roadmap items make a quiet project ready, not dormant")
    func readyFromRoadmap() {
        let result = verdict(nextSteps: 4)
        #expect(result.status == .ready)
        #expect(result.reason.contains("4 items"))
    }

    @Test("Agent branches behind integration read as blocked")
    func blockedOnIntegration() {
        var worktree = WorktreeInfo(path: "/p-claude", branch: "ai/claude", isMain: false)
        worktree.behind = 3
        let repo = RepositoryState(path: "/p", name: "app", integrationBranch: "main",
                                   worktrees: [worktree], scannedAt: now)
        let result = verdict(repository: repo)
        #expect(result.status == .blocked)
        #expect(result.reason.contains("3 commits behind"))
    }

    @Test("Quiet with nothing ready is dormant — the failure nothing else catches")
    func dormant() {
        let result = verdict(lastActivity: now.addingTimeInterval(-30 * 86_400))
        #expect(result.status == .dormant)
        #expect(result.reason.contains("30 days"))
    }

    @Test("A project inside the dormancy window is not yet dormant")
    func notYetDormant() {
        let result = verdict(lastActivity: now.addingTimeInterval(-2 * 86_400))
        #expect(result.status != .dormant)
    }

    /// A project the app knows nothing about is not a project with a problem.
    /// This used to return `.unbriefed`, rendered as a grey question mark, which
    /// read as *something is wrong here* on projects where nothing was.
    @Test("Having read no description of a project is not a status")
    func noDescriptionIsNotAStatus() {
        let result = verdict(briefs: BriefSet())
        #expect(result.status == .ready)
        #expect(result.reason == "Nothing blocked")
        // The user is never told they owe the app a file.
        #expect(!result.reason.contains("PRODUCT.md"))
        #expect(!result.reason.lowercased().contains("add"))
    }

    /// Whichever context files exist, the verdict is the same — because the
    /// verdict never depended on them. Kept as a regression guard: a later rung
    /// keyed to `meetsMinimum` would reintroduce exactly the bug removed here.
    @Test("The status is identical with and without a brief",
          arguments: ["none", "agents", "claude", "readme", "code", "product"])
    func statusIgnoresBriefs(_ which: String) {
        var briefs = BriefSet()
        switch which {
        case "agents": briefs.agents = true
        case "claude": briefs.claude = true
        case "readme": briefs.readme = true
        case "code": briefs.code = true
        case "product": briefs.product = true
        default: break
        }
        let result = verdict(briefs: briefs)
        #expect(result.status == .ready)
        #expect(result.reason == "Nothing blocked")
    }

    @Test("Needing you still outranks everything")
    func urgencyWins() {
        let waiting = Session.stub(id: "s", lastActivity: now, status: .needsAttention)
        let result = verdict(sessions: [waiting], briefs: BriefSet())
        #expect(result.status == .needsYou)
    }
}

@Suite("ProjectAssembler — assembly")
struct ProjectAssemblyTests {
    let now = Fixtures.auditNow

    @Test("Sessions become projects, grouped by working directory")
    func discoversProjects() throws {
        let dir = TempDir()
        let path = dir.path("app")
        dir.write(Fixtures.productBrief, to: "app/PRODUCT.md")
        dir.write(Fixtures.roadmapWithTasks, to: "app/ROADMAP.md")

        let sessions = [
            Session.stub(id: "a", project: "app", path: path, lastActivity: now, status: .working),
            Session.stub(id: "b", project: "app", path: path, lastActivity: now, status: .working)
        ]
        let projects = ProjectAssembler().assemble(records: [], sessions: sessions, waves: [],
                                                   repositories: [], config: Configuration(), now: now)

        let project = try #require(projects.first)
        #expect(projects.count == 1)
        #expect(project.sessions.count == 2)
        #expect(project.oneLiner?.hasPrefix("Saga is a reading app") == true)
        #expect(project.progress?.summary == "2 of 7")
        #expect(project.nextSteps.count == 5)
    }

    @Test("A recorded project with no sessions still appears")
    func projectWithoutActivity() throws {
        // The point of the record: a project you filed but haven't started is
        // exactly the one that would otherwise vanish.
        let record = ProjectRecord(id: "idea-1", name: "New idea",
                                   createdAt: now.addingTimeInterval(-60))
        let projects = ProjectAssembler().assemble(records: [record], sessions: [], waves: [],
                                                   repositories: [], config: Configuration(), now: now)

        let project = try #require(projects.first)
        #expect(project.name == "New idea")
        #expect(project.path == nil)
        #expect(project.sessions.isEmpty)
    }

    @Test("The home directory doesn't become a project")
    func homeIsNotAProject() {
        // A session run from ~ is a session, not a project, and left unfiltered
        // it becomes a permanent unbriefed row nobody can ever satisfy.
        let session = Session.stub(id: "s", project: "me", path: NSHomeDirectory(), lastActivity: now)
        let projects = ProjectAssembler().assemble(records: [], sessions: [session], waves: [],
                                                   repositories: [], config: Configuration(), now: now)
        #expect(projects.isEmpty)
    }

    @Test("The rule excludes home and its ancestors — and nothing else")
    func plausibleProjectPaths() {
        #expect(FileSupport.isPlausibleProjectPath(NSHomeDirectory()) == false)
        #expect(FileSupport.isPlausibleProjectPath("/") == false)
        #expect(FileSupport.isPlausibleProjectPath(NSHomeDirectory() + "/") == false)

        #expect(FileSupport.isPlausibleProjectPath(NSHomeDirectory() + "/projects/app"))
        // A project outside the home directory is ordinary, not suspicious — an
        // over-strict rule here silently hides real work.
        #expect(FileSupport.isPlausibleProjectPath("/opt/work/repo"))
        #expect(FileSupport.isPlausibleProjectPath("/Volumes/External/client-site"))
    }

    @Test("Ordering is pinned, then urgency, then recency")
    func ordering() throws {
        let dir = TempDir()
        dir.makeDirectory("quiet")
        dir.makeDirectory("busy")
        dir.makeDirectory("urgent")

        var pinned = ProjectRecord(id: "p-pin", name: "pinned", path: dir.path("quiet"), createdAt: now)
        pinned.isPinned = true

        let sessions = [
            Session.stub(id: "b", project: "busy", path: dir.path("busy"), lastActivity: now, status: .working),
            Session.stub(id: "u", project: "urgent", path: dir.path("urgent"), lastActivity: now, status: .needsAttention)
        ]
        let projects = ProjectAssembler().assemble(records: [pinned], sessions: sessions, waves: [],
                                                   repositories: [], config: Configuration(), now: now)

        #expect(projects.first?.name == "pinned")
        let rest = projects.dropFirst().map(\.name)
        #expect(rest.first == "urgent")   // needsYou before working
    }

    @Test("A parked project comes back on its own once its date passes")
    func parkingExpires() {
        let expired = ProjectLifecycle.parked(until: now.addingTimeInterval(-3600))
        let current = ProjectLifecycle.parked(until: now.addingTimeInterval(3600))

        #expect(expired.resolved(now: now).isActive)
        #expect(current.resolved(now: now).isActive == false)
    }

    @Test("Progress counts checked items the reader used to discard")
    func progressFromRoadmap() throws {
        let dir = TempDir()
        dir.write(Fixtures.roadmapWithTasks, to: "app/ROADMAP.md")

        let (progress, next) = ProjectAssembler.readRoadmap(projectPath: dir.path("app"))
        let result = try #require(progress)

        #expect(result.completed == 2)
        #expect(result.total == 7)
        #expect(result.source == "ROADMAP.md")
        #expect(abs(result.fraction - 2.0 / 7.0) < 0.001)
        #expect(next.count == 5)
    }
}

@Suite("ProjectStore")
struct ProjectStoreTests {
    let now = Fixtures.auditNow

    @Test("A record round-trips through its file")
    func roundTrip() throws {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url)

        let record = ProjectRecord(id: "app-abc", name: "app", path: "/home/user/projects/app",
                                   externalRef: "linear:ENG-412", lifecycle: .archived,
                                   createdAt: now, origin: "claude:sess-1", isPinned: true)
        store.save(record)

        let loaded = try #require(store.load().first)
        #expect(loaded.id == "app-abc")
        #expect(loaded.name == "app")
        #expect(loaded.path == "/home/user/projects/app")
        #expect(loaded.externalRef == "linear:ENG-412")
        #expect(loaded.origin == "claude:sess-1")
        #expect(loaded.isPinned)
        if case .archived = loaded.lifecycle {} else { Issue.record("lifecycle lost") }
    }

    @Test("A parked date survives the round trip")
    func parkedRoundTrip() throws {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url)
        let until = now.addingTimeInterval(7 * 86_400)
        store.save(ProjectRecord(id: "a", name: "a", lifecycle: .parked(until: until), createdAt: now))

        let loaded = try #require(store.load().first)
        guard case .parked(let date) = loaded.lifecycle else {
            Issue.record("expected parked")
            return
        }
        #expect(abs(date.timeIntervalSince(until)) < 1)
    }

    @Test("Notes written into the file body are preserved across saves")
    func bodyPreserved() throws {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url)
        store.save(ProjectRecord(id: "a", name: "a", createdAt: now))

        // Saving is the precondition, so check it here rather than let a missing
        // file surface as an unexplained read error three lines later.
        #expect(store.lastWriteError == nil, "\(store.lastWriteError ?? "")")
        let file = dir.url.appendingPathComponent("a.md")
        try #require(FileManager.default.fileExists(atPath: file.path),
                     "ProjectStore.save reported success but wrote nothing to \(file.path)")

        // Someone — a person or an agent — adds notes under the front matter.
        let existing = try String(contentsOf: file, encoding: .utf8)
        try (existing + "\nSome notes I wrote by hand.\n").write(to: file, atomically: true, encoding: .utf8)

        var record = try #require(store.load().first)
        record.isPinned = true
        store.save(record)

        let after = try String(contentsOf: file, encoding: .utf8)
        #expect(after.contains("Some notes I wrote by hand."))
        #expect(after.contains("pinned: true"))
    }

    @Test("ensure() creates a record once and returns the same one after")
    func ensureIsIdempotent() throws {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        // A directory that looks like a project, since discovery now requires it.
        let project = dir.makeDirectory("app")
        dir.write("# App\n", to: "app/README.md")

        let first = try #require(store.ensure(path: project.path, now: now))
        let second = try #require(store.ensure(path: project.path, now: now))

        #expect(first.id == second.id)
        #expect(store.load().count == 1)
    }

    @Test("Discovery ignores directories that are not projects")
    func discoveryIsSelective() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))

        // A session ran here, but nobody manages it: no marker of any kind.
        let bare = dir.makeDirectory("just-a-folder")
        #expect(store.ensure(path: bare.path) == nil)
        #expect(store.load().isEmpty)

        // The user saying so is enough, marker or not.
        let named = store.ensure(path: bare.path, discovered: false)
        #expect(named?.name == "just-a-folder")
        #expect(store.load().count == 1)
    }

    @Test("A marker of any kind is enough to count as a project")
    func markersCount() throws {
        for marker in ["README.md", "package.json", "Package.swift", "Cargo.toml", "AGENTS.md"] {
            let dir = TempDir()
            let project = dir.makeDirectory("thing")
            dir.write("x", to: "thing/\(marker)")
            #expect(FileSupport.looksLikeProject(project.path), "\(marker) should mark a project")
        }
    }

    @Test("Tool-state directories are never projects, even with a marker")
    func excludedLocations() {
        let dir = TempDir()
        // A path *through* a dot-directory is tool state, not work — this is the
        // shape that produced a row for a skills folder six levels inside
        // ~/.hermes. The marker is present and deliberately not enough.
        let hidden = dir.makeDirectory(".hermes/profiles/x/skills/thing")
        dir.write("x", to: ".hermes/profiles/x/skills/thing/README.md")
        #expect(!FileSupport.looksLikeProject(hidden.path))

        // A scratch directory is excluded by having no marker, not by where it
        // lives — so a real repository cloned somewhere temporary still counts.
        let scratch = dir.makeDirectory("scratchpad")
        #expect(!FileSupport.looksLikeProject(scratch.path))
        dir.write("x", to: "scratchpad/.git")
        #expect(FileSupport.looksLikeProject(scratch.path))
    }

    @Test("Identifiers are stable for a path and distinct for lookalikes")
    func identifiers() {
        let a = ProjectRecord.identifier(forPath: "/home/user/projects/app")
        #expect(a == ProjectRecord.identifier(forPath: "/home/user/projects/app"))
        // Same last component, different project.
        #expect(a != ProjectRecord.identifier(forPath: "/home/user/archive/app"))
        #expect(a.hasPrefix("app-"))
    }

    @Test("A malformed file is skipped, not fatal")
    func malformedFile() {
        let dir = TempDir()
        dir.write("not front matter at all", to: "junk.md")
        dir.write("---\nname: no id here\n---\n", to: "partial.md")
        #expect(ProjectStore(directory: dir.url).load().isEmpty)
    }
}

@Suite("FrontMatter")
struct FrontMatterTests {

    @Test("Parses flat fields and returns the body separately")
    func parses() {
        let (fields, body) = FrontMatter.parse("""
        ---
        id: app-1
        name: My App
        lifecycle: parked:2026-09-01T00:00:00Z
        ---

        Free text below.
        """)
        #expect(fields["id"] == "app-1")
        #expect(fields["name"] == "My App")
        // A value containing colons must survive intact.
        #expect(fields["lifecycle"] == "parked:2026-09-01T00:00:00Z")
        #expect(body == "Free text below.")
    }

    @Test("A file with no front matter is all body")
    func noFrontMatter() {
        let (fields, body) = FrontMatter.parse("Just a note.")
        #expect(fields.isEmpty)
        #expect(body == "Just a note.")
    }

    @Test("Rendering quotes only what needs it, and round-trips")
    func rendering() {
        let text = FrontMatter.render(fields: [("id", "a"), ("when", "2026-09-01T00:00:00Z")], body: "Body")
        #expect(text.contains("id: a"))
        #expect(text.contains("when: \"2026-09-01T00:00:00Z\""))

        let (fields, body) = FrontMatter.parse(text)
        #expect(fields["when"] == "2026-09-01T00:00:00Z")
        #expect(body == "Body")
    }

    @Test("CRLF front matter parses — these files get edited on other machines")
    func crlfFrontMatter() {
        let (fields, _) = FrontMatter.parse("---\r\nid: a\r\nname: App\r\n---\r\n\r\nBody\r\n")
        #expect(fields["id"] == "a")
        #expect(fields["name"] == "App")
    }
}

/// The list must hold still between refreshes, and say why a project needs you.
@Suite("Project list stability and reasons")
struct ProjectListStabilityTests {
    let now = Date(timeIntervalSince1970: 1_755_252_000)

    private func project(_ name: String, status: ProjectStatus,
                         activity: TimeInterval, pinned: Bool = false) -> Project {
        var record = ProjectRecord(id: name, name: name, path: "/p/\(name)")
        record.isPinned = pinned
        return Project(record: record, status: status, statusReason: "",
                       lastActivity: now.addingTimeInterval(activity))
    }

    @Test("Sub-minute differences do not reorder the list")
    func noiseDoesNotReorder() {
        // Three idle projects, timestamps a fraction of a second apart — which is
        // what re-reading the same files produces. Ordering on raw timestamps let
        // any of these swap places between refreshes.
        let a = project("alpha", status: .dormant, activity: -0.2)
        let b = project("bravo", status: .dormant, activity: -0.5)
        let c = project("charlie", status: .dormant, activity: -0.1)

        let order = [c, a, b].sorted(by: ProjectAssembler.ordering).map(\.name)
        // Same minute, so the tiebreak decides — and it is deterministic.
        #expect(order == ["alpha", "bravo", "charlie"])

        // Whatever order they arrive in, they come out the same.
        #expect([b, c, a].sorted(by: ProjectAssembler.ordering).map(\.name) == order)
        #expect([a, b, c].sorted(by: ProjectAssembler.ordering).map(\.name) == order)
    }

    @Test("A genuinely more recent project still sorts first")
    func realRecencyStillWins() {
        let old = project("alpha", status: .dormant, activity: -3600)
        let fresh = project("zulu", status: .dormant, activity: -10)
        // An hour apart is signal, not noise — despite `zulu` losing on name.
        #expect([old, fresh].sorted(by: ProjectAssembler.ordering).map(\.name) == ["zulu", "alpha"])
    }

    @Test("Pinning and status still outrank recency")
    func prioritiesHold() {
        let pinned = project("zulu", status: .dormant, activity: -3600, pinned: true)
        let urgent = project("alpha", status: .needsYou, activity: -10)
        let idle = project("bravo", status: .dormant, activity: -5)

        let order = [idle, urgent, pinned].sorted(by: ProjectAssembler.ordering).map(\.name)
        #expect(order == ["zulu", "alpha", "bravo"])
    }
}

@Suite("Why a project needs you")
struct ProjectReasonTests {
    let now = Date(timeIntervalSince1970: 1_755_252_000)

    /// A briefed project, so the verdict reaches the waiting rung rather than
    /// stopping at "No PRODUCT.md".
    static var briefed: BriefSet {
        var set = BriefSet()
        set.product = true
        return set
    }

    private func waitingSession(reason: String?, waiting: WaitingReason?) -> Session {
        var session = Session(id: "s1", title: "instructions", projectName: "instructions",
                              projectPath: "/p/instructions", source: .claudeCode,
                              lastActivity: now.addingTimeInterval(-1020))
        session.status = .needsAttention
        session.hookStatus = .needsAttention
        session.reason = reason
        session.waiting = waiting
        return session
    }

    @Test("The project reports what the session actually said")
    func usesTheSessionsOwnWords() {
        // The screenshot that prompted this showed a project row reading "Quiet
        // and waiting" directly above a session row reading the sentence below.
        let verdict = ProjectAssembler.status(
            record: ProjectRecord(id: "p", name: "instructions", path: "/p/instructions"),
            sessions: [waitingSession(reason: "Remove uncommitted work. I'm going to fix it on remote",
                                      waiting: .approval)],
            tasks: [], repository: nil, briefs: Self.briefed,
            nextStepCount: 0, lastActivity: now.addingTimeInterval(-1020), now: now)

        #expect(verdict.status == .needsYou)
        #expect(verdict.reason.contains("Remove uncommitted work"))
        #expect(!verdict.reason.contains("Quiet and waiting"))
    }

    @Test("With no explanation it falls back to the kind of wait, then to plain English")
    func fallsBackInOrder() {
        let record = ProjectRecord(id: "p", name: "x", path: "/p/x")

        let kind = ProjectAssembler.status(
            record: record, sessions: [waitingSession(reason: nil, waiting: .approval)],
            tasks: [], repository: nil, briefs: Self.briefed,
            nextStepCount: 0, lastActivity: now.addingTimeInterval(-1020), now: now)
        #expect(kind.reason == WaitingReason.approval.label)

        let neither = ProjectAssembler.status(
            record: record, sessions: [waitingSession(reason: nil, waiting: nil)],
            tasks: [], repository: nil, briefs: Self.briefed,
            nextStepCount: 0, lastActivity: now.addingTimeInterval(-1020), now: now)
        #expect(neither.reason == "Waiting on you")
    }

    @Test("A blank explanation is treated as none, not shown as nothing")
    func blankReasonFallsThrough() {
        let verdict = ProjectAssembler.status(
            record: ProjectRecord(id: "p", name: "x", path: "/p/x"),
            sessions: [waitingSession(reason: "   ", waiting: .question)],
            tasks: [], repository: nil, briefs: Self.briefed,
            nextStepCount: 0, lastActivity: now.addingTimeInterval(-1020), now: now)
        #expect(verdict.reason == WaitingReason.question.label)
    }
}


@Suite("Worktrees belong to their repository")
struct WorktreeAttributionTests {

    /// A repository with a worktree beside it, laid out the way git does.
    private func repoAndWorktree(_ dir: TempDir) -> (repo: String, worktree: String) {
        let repo = dir.makeDirectory("app")
        dir.write("ref: refs/heads/main\n", to: "app/.git/HEAD")

        let worktree = dir.makeDirectory("app-claude")
        // A worktree's `.git` is a *file*, not a directory.
        dir.write("gitdir: \(repo.path)/.git/worktrees/app-claude\n", to: "app-claude/.git")
        return (repo.path, worktree.path)
    }

    @Test("A worktree resolves to the repository it is a checkout of")
    func resolvesToRepository() {
        let dir = TempDir()
        let (repo, worktree) = repoAndWorktree(dir)
        #expect(FileSupport.mainRepository(ofWorktree: worktree) == FileSupport.normalise(repo))
    }

    @Test("An ordinary repository is not a worktree")
    func repositoryIsNotAWorktree() {
        let dir = TempDir()
        let (repo, _) = repoAndWorktree(dir)
        // Its `.git` is a directory, which is the whole distinction.
        #expect(FileSupport.mainRepository(ofWorktree: repo) == nil)
    }

    @Test("A gitdir pointing somewhere else is left alone")
    func submodulesAreNotWorktrees() {
        let dir = TempDir()
        let sub = dir.makeDirectory("vendor/lib")
        // Submodules also use a `.git` file, and must not be mistaken for a
        // worktree and folded into a parent that has nothing to do with them.
        dir.write("gitdir: ../../.git/modules/lib\n", to: "vendor/lib/.git")
        #expect(FileSupport.mainRepository(ofWorktree: sub.path) == nil)
    }

    @Test("Discovering a worktree records the repository, not the worktree")
    func discoveryFoldsWorktrees() throws {
        let dir = TempDir()
        let (repo, worktree) = repoAndWorktree(dir)
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))

        let record = try #require(store.ensure(path: worktree))
        #expect(FileSupport.pathsEqual(record.path ?? "", repo))
        #expect(record.name == "app")
        // One project, not two — the worktree and the repository are one thing.
        #expect(store.load().count == 1)
        #expect(store.ensure(path: repo)?.id == record.id)
    }
}

@Suite("Forgetting projects that are gone")
struct VanishedProjectTests {

    @Test("A discovered project whose directory is gone is dropped")
    func dropsVanished() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        let real = dir.makeDirectory("still-here")

        store.save(ProjectRecord(id: "here", name: "still-here", path: real.path))
        store.save(ProjectRecord(id: "gone", name: "gone", path: dir.path("never-existed")))

        let removed = store.forgetVanished()
        #expect(removed.map(\.id) == ["gone"])
        #expect(store.load().map(\.id) == ["here"])
    }

    @Test("A project the user added by hand is never dropped")
    func keepsManualProjects() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        // Deliberate even though the path is missing: they said this is a
        // project, and an unmounted volume or a repo not yet cloned is their
        // business, not ours to tidy away.
        store.save(ProjectRecord(id: "mine", name: "mine",
                                 path: dir.path("not-cloned-yet"), origin: "manual"))

        #expect(store.forgetVanished().isEmpty)
        #expect(store.load().count == 1)
    }

    @Test("A project with no path is left alone")
    func keepsPathlessProjects() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        // An idea rather than a checkout — there is no directory to be missing.
        store.save(ProjectRecord(id: "idea", name: "Redesign onboarding"))

        #expect(store.forgetVanished().isEmpty)
        #expect(store.load().count == 1)
    }
}

@Suite("Migrating rows that should never have existed")
struct ProjectMigrationTests {

    @Test("A worktree already recorded as its own project is folded into the repository")
    func migratesStoredWorktrees() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        let repo = dir.makeDirectory("app")
        dir.write("ref: refs/heads/main\n", to: "app/.git/HEAD")
        let worktree = dir.makeDirectory("app-agent")
        dir.write("gitdir: \(repo.path)/.git/worktrees/app-agent\n", to: "app-agent/.git")

        // Recorded before the rule existed — which is the case that matters,
        // since `ensure` returns an existing record before any check runs and
        // would never re-examine it.
        store.save(ProjectRecord(id: "wt", name: "app-agent", path: worktree.path))

        let removed = store.forgetVanished()
        #expect(removed.map(\.id) == ["wt"])

        let remaining = store.load()
        #expect(remaining.count == 1)
        #expect(FileSupport.pathsEqual(remaining[0].path ?? "", repo.path))
    }

    @Test("Forgetting removes a project whatever created it")
    func forgetRemovesAnything() {
        let dir = TempDir()
        let store = ProjectStore(directory: dir.url.appendingPathComponent("store"))
        // Manual, and its directory exists — so no automatic rule would touch it.
        // Saying "this is not a project" has to work regardless.
        let real = dir.makeDirectory("kept")
        store.save(ProjectRecord(id: "mine", name: "kept", path: real.path, origin: "manual"))

        store.forget(id: "mine")
        #expect(store.load().isEmpty)
    }
}

